# Generated by Django 4.2.6 on 2023-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='projects.category', verbose_name='Categorías'),
        ),
    ]
