# Generated by Django 4.2.6 on 2023-11-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryProj',
        ),
    ]
